# These are supported funding model platforms

github: PREETCHAUHAN # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: [PREETCHAUHAN]
patreon: DJPreet
custom: ["https://www.paypal.me/djpreet"]
paytm: [preet.6@paytm]
buy_me_a_coffee: ["https://buymeacoffee.com/djpreet3215"]
ko_fi: ["https://ko-fi.com/djpreet"]